### ISSUE TITLE
Index out of range for Zhang_suen

### ISSUE THREAD

**Issue by gregoiregentil** [arnaud-ramey/voronoi#2]
There is a very painful bug in this class that is coming randomly. After investigating, I think the bug is here:

https://github.com/arnaud-ramey/voronoi/blob/master/src/voronoi.h#L505

```
        for (int row = 0; row < rows; ++row) {
          for (int col = 0; col < cols; ++col) {
            //printf("Checking (%i, %i)...\n", col, row);
            if (*skelcontour_ptr++ == ImageContour::CONTOUR &&
                voronoi_fn(skelcontour_data, iter, col, row, cols)) {

```

See gdb info below for the resulting index out of range.

A potential fix could be to add:

```
  static bool inline need_set_zhang_suen(uchar*  skeldata, int iter, int col, int row, int cols) {
if ((row-1) * cols + col-1 < 0) return false; 
```

But it's not fixing at the source of the problem,

Grégoire

$ gdb ./program
GNU gdb (Ubuntu 7.7.1-0ubuntu5~14.04.2) 7.7.1
Copyright (C) 2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later http://gnu.org/licenses/gpl.html
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
http://www.gnu.org/software/gdb/bugs/.
Find the GDB manual and other documentation resources online at:
http://www.gnu.org/software/gdb/documentation/.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./courtcalibration...done.
(gdb) run ~/v/20160804_171757/cama.png
Starting program: program a.png
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Finding corners (0)
[New Thread 0x7fffe7296700 (LWP 14123)]
[New Thread 0x7fffe6a94700 (LWP 14125)]
[New Thread 0x7fffe6e95700 (LWP 14124)]

Program received signal SIGSEGV, Segmentation fault.
0x0000000000415d3b in VoronoiThinner::need_set_zhang_suen (skeldata=0x7ffff7f79020 "", iter=0, col=3, row=0, cols=256) at voronoi.h:546
546        bool p2 = skeldata[(row-1) \* cols + col];
(gdb) bt
#0  0x0000000000415d3b in VoronoiThinner::need_set_zhang_suen (skeldata=0x7ffff7f79020 "", iter=0, col=3, row=0, cols=256) at voronoi.h:546
#1  0x0000000000415a78 in VoronoiThinner::thin_fast_custom_voronoi_fn (this=0x7fffffffcbf0, img=..., voronoi_fn=0x415d0b <VoronoiThinner::need_set_zhang_suen(unsigned char*, int, int, int, int)>, crop_img_before=false, max_iters=2147483647) at voronoi.h:509
#2  0x000000000041527d in VoronoiThinner::thin_zhang_suen_fast (this=0x7fffffffcbf0, img=..., crop_img_before=false, max_iters=2147483647) at voronoi.h:396
#3  0x0000000000413ab5 in VoronoiThinner::thin (this=0x7fffffffcbf0, img=..., implementation_name="zhang_suen_fast", crop_img_before=false, max_iters=2147483647) at voronoi.h:116
#4  0x0000000000409790 in CourtCalibration::findCorners (this=0x631ea0 <ccp>) at courtCalibration.cpp:730
#5  0x000000000040e502 in courtCalibrationfromImage (imgPath=0x7fffffffdb80 "a.png", w=-1, h=-1, colorType=-1, id=0, calibPath=0x0) at courtCalibration.cpp:1347
#6  0x0000000000403f4e in main ()

**Comment by arnaud-ramey** [comment]
Hello @gregoiregentil ,

Thanks for the bug report. Sorry for the delay, I've been busy for the last few weeks... Did you identify the bug more accurately? Otherwise, could you supply an image that produces this bug? I will investigate the issue more in depth.

Thanks!

**Comment by gregoiregentil** [comment]
I'm pretty sure of the bug. If you read the code carefully, you will realize that you can go out of bound of the array, towards the upper left corner. It's a little bit old now so I lost the image. I'm using the code with the fix I suggested and it doesn't crash any more.

**Comment by arnaud-ramey** [comment]
Good job then. Can you propose it as a pull request? Thanks in advance.

**Comment by gregoiregentil** [comment]
I don't think it's a good fix. Because, each time, the algo is doing the 
check. A proper fix upstream in the algo stack to avoid corner issue. Do 
you see what I mean?

Grégoire
